# Generated by Django 4.1 on 2022-11-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages_my', '0002_remove_dialog_user_id_message_id_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='id_read',
            new_name='is_read',
        ),
    ]
