# Generated by Django 4.1 on 2022-11-04 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_card_options_alter_cardphoto_card_img'),
        ('messages_my', '0003_rename_id_read_message_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user_id',
        ),
        migrations.AddField(
            model_name='dialog',
            name='card_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='card_id', to='ads.card', verbose_name='Карточка'),
            preserve_default=False,
        ),
    ]
