# Generated by Django 4.1 on 2022-10-20 12:47

import apps.categories.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявлении'},
        ),
        migrations.AddField(
            model_name='card',
            name='condition',
            field=models.CharField(choices=[(1, 'Новое'), (2, 'Б\\у')], default=1, max_length=50, verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='card',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='card',
            name='id_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='category_card', to='categories.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='card',
            name='id_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_card', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='card',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалить'),
        ),
        migrations.AddField(
            model_name='card',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='slug',
            field=models.SlugField(default=None, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='title',
            field=models.CharField(default=None, max_length=50, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_img',
            field=models.ImageField(blank=True, null=True, upload_to='categories/category_img/', verbose_name='Фото категории'),
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('id_user', 'slug')},
        ),
        migrations.CreateModel(
            name='CardPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_img', models.ImageField(blank=True, null=True, upload_to=apps.categories.utils.upload_images, verbose_name='Фотографии')),
                ('id_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='categories.card')),
            ],
        ),
    ]
