# Generated by Django 4.1 on 2022-11-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_my', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialog',
            name='user_id',
        ),
        migrations.AddField(
            model_name='message',
            name='id_read',
            field=models.BooleanField(default=False),
        ),
    ]
