# Generated by Django 4.1 on 2022-11-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages_my', '0004_remove_message_user_id_dialog_card_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='dialog_id',
        ),
        migrations.DeleteModel(
            name='Dialog',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
