# Generated by Django 4.1 on 2022-10-20 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0002_alter_card_options_card_condition_card_date_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='category_card', to='categories.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='card',
            name='id_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_card', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
