# Generated by Django 4.1 on 2022-10-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_card_id_category_alter_card_id_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='cardphoto',
            options={'verbose_name': 'Фотографии', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterField(
            model_name='card',
            name='condition',
            field=models.CharField(choices=[('Новое', 'Новое'), ('Б\\у', 'Б\\у')], default='Новое', max_length=50, verbose_name='Состояние'),
        ),
    ]
