# Generated by Django 4.1 on 2022-10-20 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_card_options_alter_cardphoto_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardphoto',
            name='id_card',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='CardPhoto',
        ),
    ]
