# Generated by Django 4.1 on 2022-10-17 15:40

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='Не заполнено', max_length=128, region='RU', verbose_name='Номер телефона'),
        ),
    ]
