# Generated by Django 4.1 on 2022-10-20 15:29

import apps.categories.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0005_remove_cardphoto_id_card_delete_card_and_more'),
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('condition', models.CharField(choices=[('Новое', 'Новое'), ('Б\\у', 'Б\\у')], default='Новое', max_length=50, verbose_name='Состояние')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалить')),
                ('id_category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='category_card', to='categories.category', verbose_name='Категория')),
                ('id_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_card', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'unique_together': {('id_user', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CardPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_img', models.ImageField(blank=True, null=True, upload_to=apps.categories.utils.upload_images, verbose_name='Фотографии')),
                ('id_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='ads.card')),
            ],
            options={
                'verbose_name': 'Фотографии',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.DeleteModel(
            name='CardProduct',
        ),
    ]
