# Generated by Django 4.1 on 2022-10-29 13:34

import apps.ads.validators
import apps.categories.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_card_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-date_add'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterField(
            model_name='cardphoto',
            name='card_img',
            field=models.ImageField(blank=True, null=True, upload_to=apps.categories.utils.upload_images, validators=[apps.ads.validators.max_file_size], verbose_name='Фотографии'),
        ),
    ]
