# Generated by Django 4.1 on 2022-11-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_card_options_alter_cardphoto_card_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Архив'),
        ),
    ]
