# Generated by Django 4.1 on 2022-11-18 09:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_date_add_alter_feedback_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='date_add',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=ckeditor.fields.RichTextField(verbose_name='Отзыв'),
        ),
    ]
